{% set name = "gcloud-aio-taskqueue" %}
{% set version = "6.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: c52815e436e888f84600e34f2e287e30f2038f159c0b9ab29201d64e680ec65b

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.6,<4.0
    - pip
    - poetry-core >=1.0.0
  run:
    - python >=3.6,<4.0
    - backoff >=1.0.0,<2.0.0
    - gcloud-aio-auth >=3.1.0,<5.0.0

test:
  imports:
    - gcloud.aio.taskqueue
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/talkiq/gcloud-aio
  summary: Python Client for Google Cloud Task Queue
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - xylar
